# NumPy Operations

In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr2 = arr + arr
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr3 = arr - arr
arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr4 = arr * arr
arr4

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
arr5 = arr + 100
arr5

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [13]:
arr6 = arr + 5*2
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr7 = arr / arr
arr7
# the code still continue to run (not error) despite you can't divide 0 by 0

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
arr8 = 1 / arr
arr8
# dividing 1 to zero will give you inf

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [19]:
arr9 = arr ** 3
arr9

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

# Universal Array Function
Numpy comes with many array functions which are essentially a mathematical operations you can use to perform the operation and broadcast throughout the entire array

In [20]:
np.sqrt(arr4) # square root

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.exp(arr4) # exponential

array([1.00000000e+00, 2.71828183e+00, 5.45981500e+01, 8.10308393e+03,
       8.88611052e+06, 7.20048993e+10, 4.31123155e+15, 1.90734657e+21,
       6.23514908e+27, 1.50609731e+35, 2.68811714e+43])

In [22]:
np.max(arr4)

100

In [23]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [24]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [26]:
np.log(arr) # log 0 is negative infinity

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
# To see all the universal array function, you can checkout the notebook 
# 02 - numpy ; 03 - operations