# NumPy Arrays

In [2]:
my_list = [1,2,3,4]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

array([1, 2, 3, 4])

In [5]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,3)) # (rows,columns)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# linspace
Linear spacing ngasih nilai dengan besar nilai yang sama antar masing-masing nilai

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.linspace(1,5,11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

# Identity Matrix

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random Generator

In [38]:
np.random.rand(2) # rand is uniformly distributed

array([0.57574094, 0.14831837])

In [39]:
np.random.rand()

0.23923933537569875

In [41]:
np.random.rand(3,3)

array([[0.30781566, 0.69336744, 0.96632135],
       [0.33324212, 0.32353681, 0.54600031],
       [0.68148436, 0.39826011, 0.84434764]])

In [42]:
np.random.randn(4,4) # randn is standard normal distribution / gaussian distribution ~ centered around 0

array([[-0.36561873,  0.66041158, -0.42647449,  0.00628869],
       [-0.44837173,  1.06591365, -0.35564577,  1.7927197 ],
       [ 0.39575109,  0.32555339, -0.16390504, -0.33505176],
       [-1.74672058,  1.04065603, -1.43127925,  0.06231097]])

In [43]:
np.random.randn()

-0.08117982851962587

In [47]:
np.random.randint(1,100)

45

In [48]:
np.random.randint(1,100,2)

array([18, 41])

In [52]:
np.random.randint(1,100,(2,3)) # (low,high(exclude),size)

array([[64, 19, 21],
       [76, 51, 24]])

# Array objects

In [62]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [60]:
arr.reshape(10)

ValueError: cannot reshape array of size 50 into shape (10,)

In [58]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 50 into shape (5,5)

In [59]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
randarr = np.random.randint(1,25,20)
randarr

array([17,  6, 23, 13, 11, 23,  4, 18, 20, 10, 19,  3, 22, 19,  8, 22, 21,
       12,  9, 16])

In [67]:
randarr.reshape(4,5)

array([[21,  6, 10, 19,  7],
       [ 6, 18,  7,  9,  5],
       [ 6,  3,  2,  4, 11],
       [ 8, 23, 14, 14,  1]])

# Finding max, min, and index location

In [68]:
randarr.max()

23

In [69]:
randarr.min()

1

In [90]:
randarr = np.random.randint(1,25,20)
randarr

array([11, 21,  9, 16,  9,  4,  5, 11,  2, 20, 12,  5, 17, 20, 15,  1, 21,
        9, 21,  7])

In [91]:
randarr.argmax() # index location of the max value

1

In [92]:
randarr.argmin() # index location of the min value

15

In [98]:
randarr.shape

(4, 5)

In [99]:
randarr = randarr.reshape(1,20)
randarr

array([[11, 21,  9, 16,  9,  4,  5, 11,  2, 20, 12,  5, 17, 20, 15,  1,
        21,  9, 21,  7]])

In [100]:
randarr.shape

(1, 20)

In [95]:
randarr = randarr.reshape(4,5)
randarr

array([[11, 21,  9, 16,  9],
       [ 4,  5, 11,  2, 20],
       [12,  5, 17, 20, 15],
       [ 1, 21,  9, 21,  7]])

In [96]:
randarr.shape

(4, 5)

# Data type in this array

In [102]:
randarr.dtype # data type

dtype('int32')

# Other way to not write np. by calling numpy function

In [103]:
from numpy.random import randint

In [104]:
randint(1,10,5)

array([8, 2, 3, 1, 7])