# NumPy Indexing and Selection

In [2]:
import numpy as np

In [9]:
arr = np.random.randint(0,50,11)
arr

array([37, 37, 29, 12, 30, 47,  5, 20, 22, 35, 25])

In [10]:
arr[8]

22

In [12]:
arr[0:5]

array([37, 37, 29, 12, 30])

In [13]:
arr[:3]

array([37, 37, 29])

In [15]:
arr[2:]

array([29, 12, 30, 47,  5, 20, 22, 35, 25])

In [21]:
arr[0:4] = np.random.randint(0,15) # we can broadcast the value of arr[0:4]
arr

array([ 5,  5,  5,  5, 30, 47,  5, 20, 22, 35, 25])

In [23]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [28]:
slice_of_arr[:] = 50
slice_of_arr

array([50, 50, 50, 50, 50, 50])

In [32]:
arr
# The original arr are also changed
# That means the data are not copied, it's a view to the original array
# The reason is to avoid memory issues with very large arrays => numpy isn't automatically set copies arrays

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

# copying array without changing the original one

In [34]:
arr_copy = arr.copy()
arr_copy

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [37]:
arr_copy[0:6] = np.random.randint(6,11)
arr_copy

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [38]:
arr

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

# Indexing a into the array a.k.a. matrix

In [41]:
arr_2d = np.array([[2,4,6],[8,10,12],[14,16,18]])
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [42]:
arr_2d[1][1]

10

In [43]:
arr_2d[2,1]

16

In [48]:
arr_2d[:2,:]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [49]:
arr_2d[:2,1:]

array([[ 4,  6],
       [10, 12]])

In [50]:
arr_2d[1:,:]

array([[ 8, 10, 12],
       [14, 16, 18]])

# Conditional selection

In [53]:
arrC = np.arange(1,11)
arrC

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
bool_arr = arrC == 5
bool_arr

array([False, False, False, False,  True, False, False, False, False,
       False])

In [57]:
arrC[bool_arr] # will only get the result where the boolean is true

array([5])

In [62]:
bool2_arr = arrC <= 3
bool2_arr

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [63]:
arrC[bool2_arr]

array([1, 2, 3])

In [64]:
# latihan dewe

In [66]:
Arr = np.random.randint(1,50,10)
Arr

array([ 2, 25, 13, 38, 32, 34, 29, 28, 43, 29])

In [69]:
bool_Arr = Arr <= 25
bool_Arr

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [71]:
Arr[bool_Arr]

array([ 2, 25, 13])

In [72]:
## YOU CAN DO THIS INSTEAD

In [73]:
Arr[Arr<=25]

array([ 2, 25, 13])

In [79]:
Arr_2d = np.arange(1,51).reshape(5,10)
Arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [82]:
Arr_2d[:,9]

array([10, 20, 30, 40, 50])

In [83]:
Arr_2d[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])